### ISSUE TITLE
Missing Gear-Group 5 and 6

### ISSUE THREAD

**Issue by SentinelMantik** [BarryCarlyon/FS22_ExtraGears#1]
The vanilla version of FS22 is missing group 5/6. 

I extended your Mod, maybe you want to include it in yours and put an update in modhub

[FS22_ExtraGears.zip](https://github.com/BarryCarlyon/FS22_ExtraGears/files/7652751/FS22_ExtraGears.zip)

**Comment by BarryCarlyon** [comment]
Interesting I didn't know the game had a group 5/6

I'll look this over and get it added in

**Comment by SentinelMantik** [comment]
I don't. The Base-Game only has a 5 Group one like the JD 7810.  But maybe theres a simple mod to try it.
 i could try and botch a test vehicle if needed

**Comment by BarryCarlyon** [comment]
👍 that should do the trick for testing with. If it works for group 5 it'll work for group 6 too
