### ISSUE TITLE
Help; Crash to desktop on exit to main menu (Not just this mod)

### ISSUE THREAD

**Issue by StevenT72** [BarryCarlyon/FS22_ExtraGears#3]
Ive been trying to find out why my game crashes to desktop on exit to main menu. Ive asked Giants but got "Unable to reproduce without mods" but I found it only happens when mods like Extra Gears or Power Tools are running. Any mod that put in a item such as a tractor or building the game exits to main menu like normal. With mods like Extra Gears, Power Tools, Guidance Steering and the like it will crash on exit. There are others on reddit who have the same issue. Any idea to the issue? Not saying your mod is the culprit but seams all mods with LUA code maybe. Just looking for answers. I run on PC by the way.

**Comment by BarryCarlyon** [comment]
I oberseved this too.

Not sure where the issue is. When I get some time I'll do some digging, it's a super weird one

**Comment by StevenT72** [comment]
That's what I believe too. Base game issue. Guess we wait until Giants silently fixes it and leaves it out of the patch notes.

**Comment by BarryCarlyon** [comment]
Oh this seems to no longer be happened. So looks like they fixed it?
